<Project Sdk="Microsoft.NET.Sdk">

	<!--<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>-->

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="$(CoverletCollectorVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertionsVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(MicrosoftEntityFrameworkCoreInMemoryVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftNETTestSdkVersion)" />
    <PackageReference Include="Moq" Version="$(MoqVersion)" />
    <PackageReference Include="xunit" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVisualStudioVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaCollection.Business\MediaCollection.Business.csproj" />
    <ProjectReference Include="..\MediaCollection.Domain\MediaCollection.Domain.csproj" />
  </ItemGroup>

	<!--other way to do globalusings-->
  <ItemGroup>
    <Using Include="Xunit" />
	<Using Include="FluentAssertions" />
	<Using Include="Moq" />
	<Using Include="System.Diagnostics.CodeAnalysis" />
  </ItemGroup>

</Project>
