<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaCollection.Business\MediaCollection.Business.csproj" />
    <ProjectReference Include="..\MediaCollection.Data\MediaCollection.Data.csproj" />
    <ProjectReference Include="..\MediaCollection.Domain\MediaCollection.Domain.csproj" />
  </ItemGroup>

</Project>
