// <auto-generated />
using System;
using MediaCollection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaCollection.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20241024174112_AddedPictureUriProperty")]
    partial class AddedPictureUriProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaCollection.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe639e17-33b5-4760-902a-505f1d2c1a39"),
                            Name = "Neil Gaiman",
                            PictureUri = "https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1687,w_2999,x_0,y_0/dpr_1.5/c_limit,w_1600/fl_lossy,q_auto/v1610347631/210108-leon-neil-gaiman-hero_vhtgng"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bce51c1-e109-453d-8636-a23b491dd98f"),
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = new Guid("a0ce19a0-44ab-43c0-a509-a3e14efb1e83"),
                            Name = "ZA/UM",
                            PictureUri = "https://videogames.si.com/.image/t_share/MjA0MzY3MDI4MDcxNDQyMjA4/zaum-studio-logo-1.png"
                        },
                        new
                        {
                            Id = new Guid("9321e4f8-95d6-4ab8-9ed8-b9969ff29f78"),
                            Name = "Square Product Development Division 1"
                        },
                        new
                        {
                            Id = new Guid("0f23d874-d359-4981-8666-67a3797af7be"),
                            Name = "Yacht Club Games"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4b3c368-71ff-4087-b104-861471a0984e"),
                            Name = "George Miller",
                            PictureUri = "https://i1.wp.com/www.filminquiry.com/wp-content/uploads/2020/05/George-Miller.jpg?fit=1050%2C700&ssl=1"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Owned")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Media");

                    b.HasDiscriminator().HasValue("Media");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29bd7012-e575-4e2b-9f81-d7791d3bcb8f"),
                            Name = "HarperTorch"
                        },
                        new
                        {
                            Id = new Guid("5a8fa818-4244-4787-97b7-b030aa4c1eb2"),
                            Name = "Warner Bros. Pictures",
                            PictureUri = "https://www.fotolip.com/wp-content/uploads/2016/05/Warner-Bros-logo-23.jpg"
                        },
                        new
                        {
                            Id = new Guid("109def28-5d47-4efe-ab62-eb3cd170eb97"),
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = new Guid("f5e844a0-764d-4a3a-aa86-9ba142c0336e"),
                            Name = "Square",
                            PictureUri = "https://www.square-enix-games.com/home/public/selogo_onwhite.jpg"
                        },
                        new
                        {
                            Id = new Guid("1aac03f1-2841-439d-84e0-799860803fdf"),
                            Name = "ZA/UM",
                            PictureUri = "https://videogames.si.com/.image/t_share/MjA0MzY3MDI4MDcxNDQyMjA4/zaum-studio-logo-1.png"
                        },
                        new
                        {
                            Id = new Guid("e5487813-42fe-4688-a2c4-6e84aa49a326"),
                            Name = "Yacht Club Games",
                            PictureUri = "https://images.nintendolife.com/9081f8a938747/yacht-club-games.original.jpg"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Book", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AuthorId");

                    b.HasDiscriminator().HasValue("Book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcb9561e-b753-4269-af33-480958964d4d"),
                            Name = "American Gods",
                            Owned = true,
                            PictureUri = "https://1.bp.blogspot.com/-sIcmR6Ve9uk/UT4G1N7iAaI/AAAAAAAASJU/KEzdlynscVE/s1600/american-gods-ebook-9788499185415.jpg",
                            PublisherId = new Guid("29bd7012-e575-4e2b-9f81-d7791d3bcb8f"),
                            ReleaseDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthorId = new Guid("fe639e17-33b5-4760-902a-505f1d2c1a39")
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Film", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("DirectorId");

                    b.HasDiscriminator().HasValue("Film");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9742b9c-146c-4b31-82a1-d8ff3ead20e4"),
                            Name = "Mad Max: Fury Road",
                            Owned = false,
                            PictureUri = "https://cdn.traileraddict.com/content/warner-bros-pictures/mad_max_fury_road-7.jpg",
                            PublisherId = new Guid("5a8fa818-4244-4787-97b7-b030aa4c1eb2"),
                            ReleaseDate = new DateTime(2015, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DirectorId = new Guid("d4b3c368-71ff-4087-b104-861471a0984e")
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Game", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("OwnedOn")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DeveloperId");

                    b.HasDiscriminator().HasValue("Game");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b239517a-59ca-486f-a9bd-5eaff6e24743"),
                            Name = "Hades",
                            Owned = true,
                            PictureUri = "https://image.api.playstation.com/vulcan/ap/rnd/202104/0517/9AcM3vy5t77zPiJyKHwRfnNT.png",
                            PublisherId = new Guid("109def28-5d47-4efe-ab62-eb3cd170eb97"),
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("4bce51c1-e109-453d-8636-a23b491dd98f"),
                            Finished = true,
                            OwnedOn = "Steam"
                        },
                        new
                        {
                            Id = new Guid("2b1458d6-3758-42d0-aeb2-8ded3611120e"),
                            Name = "Disco Elysium",
                            Owned = true,
                            PictureUri = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2022/10/disco-elysium-final-cut.jpg",
                            PublisherId = new Guid("1aac03f1-2841-439d-84e0-799860803fdf"),
                            ReleaseDate = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("a0ce19a0-44ab-43c0-a509-a3e14efb1e83"),
                            Finished = false,
                            OwnedOn = "GOG"
                        },
                        new
                        {
                            Id = new Guid("bb916761-0f0f-40e9-a3c5-e49b55bdd05c"),
                            Name = "Shovel Knight",
                            Owned = true,
                            PictureUri = "https://www.gamespot.com/a/uploads/scale_medium/mig/0/0/6/2/2230062-box_sk.png",
                            PublisherId = new Guid("e5487813-42fe-4688-a2c4-6e84aa49a326"),
                            ReleaseDate = new DateTime(2014, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("0f23d874-d359-4981-8666-67a3797af7be"),
                            Finished = true,
                            OwnedOn = "Steam"
                        },
                        new
                        {
                            Id = new Guid("4d9e6cc9-212c-4292-b211-1fcb6d362f25"),
                            Name = "Final Fantasy 10",
                            Owned = true,
                            PictureUri = "https://m.media-amazon.com/images/I/91rQrZ+BRHL._AC_SL1500_.jpg",
                            PublisherId = new Guid("f5e844a0-764d-4a3a-aa86-9ba142c0336e"),
                            ReleaseDate = new DateTime(2002, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("9321e4f8-95d6-4ab8-9ed8-b9969ff29f78"),
                            Finished = true,
                            OwnedOn = "Playstation 2"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Media", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Media")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Book", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Film", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Game", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Director", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
