// <auto-generated />
using System;
using MediaCollection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaCollection.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20241023221346_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaCollection.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7a76a93-4f5a-4409-aa6f-a10b08e25972"),
                            Name = "Neil Gaiman"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44834ccb-3cb8-439f-b18e-3ea8ea326e62"),
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = new Guid("4894ae09-3aba-49a6-90f2-9c9950128e79"),
                            Name = "ZA/UM"
                        },
                        new
                        {
                            Id = new Guid("e12cd967-fc5d-4ecc-bc02-ec595e7975a5"),
                            Name = "Square Product Development Division 1"
                        },
                        new
                        {
                            Id = new Guid("edb6b2e4-5325-4e32-aec1-425ce0c9329a"),
                            Name = "Yacht Club Games"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a12bf92-f007-4cda-853e-ac47afb32b58"),
                            Name = "George Miller"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Owned")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Media");

                    b.HasDiscriminator().HasValue("Media");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dd65acc-3298-4cb8-a5df-8f8c93059e04"),
                            Name = "HarperTorch"
                        },
                        new
                        {
                            Id = new Guid("0526a300-872f-4abe-825d-db8f6640408e"),
                            Name = "Warner Bros. Pictures"
                        },
                        new
                        {
                            Id = new Guid("0cbf6f06-0cb8-44cb-9525-02d4d834181c"),
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = new Guid("2d7fd4be-95be-45c7-884e-b8876bf97632"),
                            Name = "Square"
                        },
                        new
                        {
                            Id = new Guid("228f850d-ba52-4137-a9b1-7449f14f774c"),
                            Name = "ZA/UM"
                        },
                        new
                        {
                            Id = new Guid("93eefc0a-de92-4cd0-9e82-9a59e5b443c8"),
                            Name = "Yacht Club Games"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Book", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AuthorId");

                    b.HasDiscriminator().HasValue("Book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed980d9f-fc15-4cf5-844a-9b12566a8597"),
                            Name = "American Gods",
                            Owned = true,
                            PublisherId = new Guid("2dd65acc-3298-4cb8-a5df-8f8c93059e04"),
                            ReleaseDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthorId = new Guid("c7a76a93-4f5a-4409-aa6f-a10b08e25972")
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Film", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("DirectorId");

                    b.HasDiscriminator().HasValue("Film");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fff9a839-2710-46c9-96fb-fa1f585ae2e8"),
                            Name = "Mad Max: Fury Road",
                            Owned = false,
                            PublisherId = new Guid("0526a300-872f-4abe-825d-db8f6640408e"),
                            ReleaseDate = new DateTime(2015, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DirectorId = new Guid("2a12bf92-f007-4cda-853e-ac47afb32b58")
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Game", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("OwnedOn")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DeveloperId");

                    b.HasDiscriminator().HasValue("Game");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d64a24c6-7bd6-4ba8-a1a6-524d69305efe"),
                            Name = "Hades",
                            Owned = true,
                            PublisherId = new Guid("0cbf6f06-0cb8-44cb-9525-02d4d834181c"),
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("44834ccb-3cb8-439f-b18e-3ea8ea326e62"),
                            Finished = true,
                            OwnedOn = "Steam"
                        },
                        new
                        {
                            Id = new Guid("11fa67da-5ec1-4f24-a8f2-aa5fc02f9c9d"),
                            Name = "Disco Elysium",
                            Owned = true,
                            PublisherId = new Guid("228f850d-ba52-4137-a9b1-7449f14f774c"),
                            ReleaseDate = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("4894ae09-3aba-49a6-90f2-9c9950128e79"),
                            Finished = false,
                            OwnedOn = "GOG"
                        },
                        new
                        {
                            Id = new Guid("4040186e-770a-44ac-9323-1ea8107eb13d"),
                            Name = "Shovel Knight",
                            Owned = true,
                            PublisherId = new Guid("93eefc0a-de92-4cd0-9e82-9a59e5b443c8"),
                            ReleaseDate = new DateTime(2014, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("edb6b2e4-5325-4e32-aec1-425ce0c9329a"),
                            Finished = true,
                            OwnedOn = "Steam"
                        },
                        new
                        {
                            Id = new Guid("c4b4d641-041d-4a60-b1ff-32c122853751"),
                            Name = "Final Fantasy 10",
                            Owned = true,
                            PublisherId = new Guid("2d7fd4be-95be-45c7-884e-b8876bf97632"),
                            ReleaseDate = new DateTime(2002, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = new Guid("e12cd967-fc5d-4ecc-bc02-ec595e7975a5"),
                            Finished = true,
                            OwnedOn = "Playstation 2"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Media", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Media")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Book", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Film", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Game", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Director", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
