// <auto-generated />
using System;
using MediaCollection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaCollection.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20240718183105_AddedSeedDataAgain")]
    partial class AddedSeedDataAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaCollection.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NeilGaiman"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ZA/UM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Square Product Development Division 1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yacht Club Games"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "George Miller"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Owned")
                        .HasColumnType("bit");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Media");

                    b.HasDiscriminator().HasValue("Media");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HarperTorch"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Warner Bros. Pictures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Square"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ZA/UM"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yacht Club Games"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Book", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasIndex("AuthorId");

                    b.HasDiscriminator().HasValue("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "American Gods",
                            Owned = true,
                            PublisherId = 1,
                            ReleaseDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuthorId = 1
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Film", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.HasIndex("DirectorId");

                    b.HasDiscriminator().HasValue("Film");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Name = "Mad Max: Fury Road",
                            Owned = false,
                            PublisherId = 2,
                            ReleaseDate = new DateTime(2015, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DirectorId = 1
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Game", b =>
                {
                    b.HasBaseType("MediaCollection.Domain.Entities.Media");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("OwnedOn")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DeveloperId");

                    b.HasDiscriminator().HasValue("Game");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Name = "Hades",
                            Owned = true,
                            PublisherId = 3,
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 1,
                            Finished = true,
                            OwnedOn = "Steam"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Disco Elysium",
                            Owned = true,
                            PublisherId = 6,
                            ReleaseDate = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 4,
                            Finished = false,
                            OwnedOn = "GOG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shovel Knight",
                            Owned = true,
                            PublisherId = 5,
                            ReleaseDate = new DateTime(2014, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 3,
                            Finished = true,
                            OwnedOn = "Steam"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Final Fantasy 10",
                            Owned = true,
                            PublisherId = 4,
                            ReleaseDate = new DateTime(2002, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 2,
                            Finished = true,
                            OwnedOn = "Playstation 2"
                        });
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Media", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Media")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Book", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Film", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Game", b =>
                {
                    b.HasOne("MediaCollection.Domain.Entities.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Director", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("MediaCollection.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
