<Project Sdk="Microsoft.NET.Sdk">

  <!--<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>-->

  <ItemGroup>
    <ProjectReference Include="..\MediaCollection.Data\MediaCollection.Data.csproj" />
    <ProjectReference Include="..\MediaCollection.Domain\MediaCollection.Domain.csproj" />
  </ItemGroup>

</Project>
